# Generated by Django 3.1.6 on 2021-02-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaj', '0004_joblocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JOB',
        ),
    ]
