# Generated by Django 3.1.6 on 2021-02-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaj', '0006_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source_link',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
