# Generated by Django 3.1.6 on 2021-02-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaj', '0009_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Apply_start',
            new_name='apply_last_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Last_date',
            new_name='apply_start',
        ),
    ]
